# Week 2 Visual Creation Script
# Generates a clean table showing Top 5 NFL Offenses by EPA/Play for 2025 Regular Season
# 
# Usage: source("scripts/visuals/create_week2_visual.R")
# Output: output/visuals/week2_top_offenses.png

library(tidyverse)
library(nflplotR)
library(gt)
library(webshot2)

# Source required functions
source("R/01_data_loading.R")
source("R/03_team_stats.R")

# Create output directory if it doesn't exist
if (!dir.exists("output/plots")) {
  dir.create("output/plots", recursive = TRUE)
  message("Created output/plots/ directory")
}

# Load 2025 regular season data
message("Loading 2025 regular season data...")
pbp_2025 <- load_and_validate_pbp(2025)

# Get offensive stats
message("Calculating team offensive statistics...")
offense_stats <- get_team_offense_stats(pbp_2025, season = 2025)

# Prepare top 5 for visualization
top5_offenses <- offense_stats %>%
  head(5) %>%
  mutate(
    rank = row_number(),
    epa_formatted = sprintf("%.3f", offensive_epa_per_play),
    plays_formatted = format(total_plays, big.mark = ","),
    success_formatted = sprintf("%.1f%%", success_rate * 100)
  ) %>%
  select(
    Rank = rank,
    Team = team,
    `EPA/Play` = epa_formatted,
    `Total Plays` = plays_formatted,
    `Success Rate` = success_formatted
  )

message("\nTop 5 Offenses by EPA/Play:")
print(top5_offenses)

# Create GT table
message("\nCreating visualization...")

table <- top5_offenses %>%
  gt() %>%
  # Add team logos
  # Add team logos using nflplotR's function
  nflplotR::gt_nfl_logos(columns = Team) %>%
  
  # Style header
  tab_header(
    title = md("**Top 5 NFL Offenses by EPA/Play**"),
    subtitle = "2025 Regular Season • Generated by nfl-analytics-toolkit"
  ) %>%
  # Column alignment
  cols_align(
    align = "center",
    columns = everything()
  ) %>%
  cols_align(
    align = "left",
    columns = Team
  ) %>%
  # Style column headers
  tab_style(
    style = list(
      cell_fill(color = "#1E3A8A"),
      cell_text(color = "white", weight = "bold", size = px(18))
    ),
    locations = cells_column_labels()
  ) %>%
  # Highlight EPA column
  tab_style(
    style = cell_text(weight = "bold", color = "#3B82F6", size = px(20)),
    locations = cells_body(columns = `EPA/Play`)
  ) %>%
  # Zebra striping
  tab_style(
    style = cell_fill(color = "#F3F4F6"),
    locations = cells_body(rows = c(2, 4))
  ) %>%
  # Add source note
  tab_source_note(
    source_note = "Function: get_team_offense_stats() • Module: 03_team_stats.R"
  ) %>%
  # Table styling
  tab_options(
    table.width = pct(100),
    table.font.size = px(16),
    heading.title.font.size = px(28),
    heading.subtitle.font.size = px(14),
    data_row.padding = px(12),
    source_notes.font.size = px(12),
    table.border.top.style = "hidden",
    table.border.bottom.style = "hidden"
  )

# Save as PNG
output_file <- "output/plots/week2_top_offenses.png"
message("Saving visualization...")

gtsave(
  table,
  filename = output_file,
  vwidth = 1200,
  vheight = 800
)

message(glue::glue("✅ Visual saved to: {output_file}"))
